### 14. Admin Upload Image
# @name uploadAdminImage
POST {{host}}/api/admin/images
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{admin_token}}

--boundary
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< ./test.png
--boundary--

### 15. Product Images
# @name getProductImages
GET {{host}}/api/products/1/images