
CREATE TABLE Bank (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE User (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    birthDate DATE NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Product (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    bankId INT UNSIGNED NOT NULL,
    productType VARCHAR(20) NOT NULL,
    interestType VARCHAR(20) NOT NULL,
    paymentCycle INT NULL,
    totalPeriodDays INT NOT NULL,
    minPaymentAmount INT NOT NULL,
    maxPaymentAmount INT NOT NULL,
    baseRate DECIMAL(5,2) NOT NULL,
    earlyWithdrawalRate DECIMAL(5,2) NOT NULL,
    minAge INT NULL,
    maxAge INT NULL,
    depositProtectionLimit INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (bankId) REFERENCES Bank(id)
);

CREATE TABLE Account (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    userId INT UNSIGNED NOT NULL,
    productId INT UNSIGNED NOT NULL,
    accountNumber VARCHAR(30) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    principal BIGINT NOT NULL DEFAULT 0,
    accruedInterest BIGINT NOT NULL DEFAULT 0,
    appliedRate DECIMAL(5,2) NOT NULL,
    currentInstallmentCount INT UNSIGNED NOT NULL DEFAULT 0,
    paymentDay INT UNSIGNED NULL,
    lastPaidAt DATETIME NULL,
    startedAt DATETIME NOT NULL,
    maturityAt DATETIME NOT NULL,
    terminatedAt DATETIME NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(id),
    FOREIGN KEY (productId) REFERENCES Product(id)
);

CREATE TABLE Transaction (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    accountId INT UNSIGNED NOT NULL,
    transactionType VARCHAR(20) NOT NULL,
    amount INT NOT NULL,
    balanceAfter BIGINT NOT NULL,
    occurredAt DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    description VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (accountId) REFERENCES Account(id),
    INDEX idx_transaction_account_occurred (accountId, occurredAt)
);

CREATE TABLE image (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    productId INT UNSIGNED NOT NULL,
    imageUrl VARCHAR(500) NOT NULL,
    isThumbnail BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (productId) REFERENCES Product(id)
);