
CREATE TABLE Bank (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE User (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    birthDate DATE NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Product (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    bank_id INT UNSIGNED NOT NULL,
    productType VARCHAR(20) NOT NULL,
    interestType VARCHAR(20) NOT NULL,
    paymentCycle INT NULL,
    isFixed BOOLEAN NOT NULL,
    totalPeriodDays INT NOT NULL,
    minPaymentAmount INT NOT NULL,
    maxPaymentAmount INT NOT NULL,
    baseRate DECIMAL(5,2) NOT NULL,
    earlyWithdrawalRate DECIMAL(5,2) NOT NULL,
    minAge INT NULL,
    maxAge INT NULL,
    depositProtectionLimit INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (bank_id) REFERENCES Bank(id)
);

CREATE TABLE Account (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NOT NULL,
    accountNumber VARCHAR(30) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    principal BIGINT NOT NULL DEFAULT 0,
    balance BIGINT NOT NULL DEFAULT 0,
    accruedInterest BIGINT NOT NULL DEFAULT 0,
    appliedRate DECIMAL(5,2) NOT NULL,
    totalInstallmentCount INT UNSIGNED NOT NULL,
    currentInstallmentCount INT UNSIGNED NOT NULL DEFAULT 0,
    paymentDay INT UNSIGNED NULL,
    lastPaidAt DATETIME NULL,
    startedAt DATETIME NOT NULL,
    maturityAt DATETIME NOT NULL,
    terminatedAt DATETIME NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User(id),
    FOREIGN KEY (product_id) REFERENCES Product(id)
);

CREATE TABLE Transaction (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    account_id INT UNSIGNED NOT NULL,
    transactionType VARCHAR(20) NOT NULL,
    amount INT NOT NULL,
    balanceAfter BIGINT NOT NULL,
    occurredAt DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    description VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES Account(id),
    INDEX idx_transaction_account_occurred (account_id, occurredAt)
);

CREATE TABLE Image (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_id INT UNSIGNED NOT NULL,
    thumbnailPath VARCHAR(255) NOT NULL,
    imagePath VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES Product(id)
);